version: 2
updates:
  # Flutter frontend
  - package-ecosystem: "pub"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Pocketbase
  - package-ecosystem: "gomod"
    directory: "/pocketbase"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Go  api_proxy
  - package-ecosystem: "gomod"
    directory: "/api_proxy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
