services:
  api-proxy:
    image: ghcr.io/lofter1/api-proxy:dev-latest
    build:
      context: ./api_proxy
      dockerfile: Dockerfile
    container_name: api-proxy
    ports:
      - "8080:8080"
    environment:
      - METRON_USERNAME=${METRON_USERNAME}
      - METRON_PASSWORD=${METRON_PASSWORD}  
      - GCD_USERNAME=${GCD_USERNAME}
      - GCD_PASSWORD=${GCD_PASSWORD}        
      - PROXY_URL=${PROXY_URL}
      - POCKETBASE_URL=http://pocketbase:8080/
      - REDIS_ADDR=redis-api-cache:6379
    depends_on:
      - redis-api-cache
    restart: unless-stopped


  pocketbase:
    image: ghcr.io/lofter1/pocketbase:dev-latest-arm64
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: pocketbase
    ports:
      - "8090:8080"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    restart: unless-stopped

  frontend:
    image: ghcr.io/lofter1/frontend:dev-latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config/web:/webconfig
      - ./config/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  redis-api-cache:
    image: redis:7-alpine
    volumes:
      - redis-api-cache-data:/data
    restart: always
      
volumes:
  redis-api-cache-data:
  caddy_data:
  caddy_config:
