services:
  metron-proxy:
    build:
      context: ./metron_proxy
      dockerfile: Dockerfile
    container_name: metron-proxy
    ports:
      - "8080:8080"
    environment:
      - METRON_USERNAME=${METRON_USERNAME}
      - METRON_PASSWORD=${METRON_PASSWORD}      
      - METRON_PROXY_URL=${PROXY_URL}
      - POCKETBASE_URL=http://pocketbase:8080/
        - REDIS_ADDR=redis-metron-cache:6379
    depends_on:
      - redis-metron-cache
    restart: unless-stopped


  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: pocketbase
    ports:
      - "8090:8080"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8070:80"
    volumes:
      - ./config:/webconfig
    restart: unless-stopped

  redis-metron-cache:
    image: redis:7-alpine
    volumes:
      - redis-metron-cache-data:/data
    restart: always
      
volumes:
  redis-metron-cache-data:
# TODO: https://hub.docker.com/_/caddy
# This image provides for two mount-points for volumes: /data and /config.
#
# In the examples below, a named volume⁠ caddy_data is mounted to /data, so that data will be persisted.

