import plugin from 'tailwindcss/plugin.js'

const lightTheme = {
  '--ink': '#1d2328',
  '--muted': '#66746e',
  '--line': '#d8ded9',
  '--line-strong': '#c4cec8',
  '--surface': '#ffffff',
  '--surface-soft': '#f7faf8',
  '--surface-muted': '#f0f3f2',
  '--app-bg-start': '#f8faf9',
  '--app-bg-end': '#eef2f1',
  '--sidebar-bg': 'rgba(255, 255, 255, 0.88)',
  '--sticky-bg': 'rgba(248, 250, 249, 0.94)',
  '--sticky-border': 'rgba(196, 206, 200, 0.72)',
  '--panel-bg': 'rgba(255, 255, 255, 0.9)',
  '--panel-soft-bg': 'rgba(255, 255, 255, 0.74)',
  '--control-ink': '#26302b',
  '--body-copy': '#3b4741',
  '--label-ink': '#42514a',
  '--eyebrow': '#8e514b',
  '--shadow-soft': 'rgba(29, 35, 40, 0.08)',
  '--shadow-panel': 'rgba(29, 35, 40, 0.07)',
  '--focus-ring': 'rgba(59, 102, 160, 0.2)',
  '--spinner-track': '#d7e1dd',
  '--read-progress-bg': '#e5ebe8',
  '--primary': '#b64237',
  '--primary-strong': '#8e2f27',
  '--primary-soft': '#fdebea',
  '--accent': '#3b66a0',
  '--warning-soft': '#fff7e6',
  '--warning-ink': '#8a5a00',
  '--warning-border': '#e2c46a',
  '--danger': '#8d2f24',
  '--danger-soft': '#fff2ef',
  '--danger-border': '#d5a19a',
}

const darkTheme = {
  '--ink': '#e5ece8',
  '--muted': '#9cabaa',
  '--line': '#283631',
  '--line-strong': '#3a4b44',
  '--surface': '#141d19',
  '--surface-soft': '#19241f',
  '--surface-muted': '#1f2b26',
  '--app-bg-start': '#111916',
  '--app-bg-end': '#0d1210',
  '--sidebar-bg': 'rgba(16, 23, 20, 0.9)',
  '--sticky-bg': 'rgba(13, 18, 16, 0.92)',
  '--sticky-border': 'rgba(58, 75, 68, 0.76)',
  '--panel-bg': 'rgba(20, 29, 25, 0.92)',
  '--panel-soft-bg': 'rgba(25, 36, 31, 0.78)',
  '--control-ink': '#e5ece8',
  '--body-copy': '#c7d4ce',
  '--label-ink': '#c0cec8',
  '--eyebrow': '#f0aaa2',
  '--shadow-soft': 'rgba(0, 0, 0, 0.26)',
  '--shadow-panel': 'rgba(0, 0, 0, 0.34)',
  '--focus-ring': 'rgba(110, 171, 207, 0.28)',
  '--spinner-track': '#2b3933',
  '--read-progress-bg': '#25322d',
  '--primary': '#ff8a80',
  '--primary-strong': '#ffb0a8',
  '--primary-soft': '#3b211f',
  '--accent': '#78a7dc',
  '--warning-soft': '#352b17',
  '--warning-ink': '#ffd880',
  '--warning-border': '#7d6425',
  '--danger': '#ff9a8f',
  '--danger-soft': '#3b201d',
  '--danger-border': '#8a4a43',
}

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      colors: {
        ink: 'var(--ink)',
        muted: 'var(--muted)',
        line: 'var(--line)',
        'line-strong': 'var(--line-strong)',
        surface: 'var(--surface)',
        'surface-soft': 'var(--surface-soft)',
        'surface-muted': 'var(--surface-muted)',
        control: 'var(--control-ink)',
        body: 'var(--body-copy)',
        label: 'var(--label-ink)',
        eyebrow: 'var(--eyebrow)',
        primary: {
          DEFAULT: 'var(--primary)',
          strong: 'var(--primary-strong)',
          soft: 'var(--primary-soft)',
        },
        accent: 'var(--accent)',
        warning: {
          DEFAULT: 'var(--warning-ink)',
          soft: 'var(--warning-soft)',
          border: 'var(--warning-border)',
        },
        danger: {
          DEFAULT: 'var(--danger)',
          soft: 'var(--danger-soft)',
          border: 'var(--danger-border)',
        },
        focus: 'var(--focus-ring)',
        panel: 'var(--panel-bg)',
        'panel-soft': 'var(--panel-soft-bg)',
        'sticky-bg': 'var(--sticky-bg)',
        'sticky-border': 'var(--sticky-border)',
        'read-progress': 'var(--read-progress-bg)',
        'spinner-track': 'var(--spinner-track)',
        backdrop: 'rgba(7, 10, 9, 0.58)',
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'sans-serif',
        ],
      },
      maxWidth: {
        intro: '42rem',
        prose: '48rem',
        content: '72rem',
      },
      minHeight: {
        panel: '22rem',
      },
      screens: {
        'down-phone': { max: '420px' },
        'down-compact': { max: '620px' },
        'down-narrow': { max: '760px' },
        'down-mobile': { max: '720px' },
        'down-tablet': { max: '960px' },
        'down-laptop': { max: '1180px' },
        'desktop-compact': { min: '961px', max: '1440px' },
      },
      borderRadius: {
        xs: '3px',
        sm: '5px',
        DEFAULT: '8px',
        md: '9px',
        lg: '10px',
        xl: '12px',
        '2xl': '14px',
        'ui-sm': '6px',
        ui: '7px',
      },
      boxShadow: {
        soft: '0 8px 22px var(--shadow-soft)',
        panel: '0 18px 48px var(--shadow-panel)',
        elevated: '0 24px 64px var(--shadow-panel)',
        inset: 'inset 0 0 0 1px var(--line-strong)',
        focus: '0 0 0 3px var(--focus-ring)',
        interactive: '0 7px 18px var(--shadow-soft)',
        detail: '0 12px 34px var(--shadow-panel)',
        dialog: '0 18px 60px var(--shadow-panel)',
        'sticky-soft': '0 10px 22px var(--shadow-soft)',
        sticky: '0 10px 24px var(--shadow-soft)',
        overlay: '0 22px 56px var(--shadow-panel)',
        float: '0 8px 24px var(--shadow-panel)',
        monitor: '0 18px 42px var(--shadow-panel)',
        control: '0 7px 16px var(--shadow-soft)',
        selected: 'inset 3px 0 0 var(--primary), 0 8px 18px var(--shadow-soft)',
      },
      backgroundImage: {
        app: 'linear-gradient(180deg, var(--app-bg-start) 0%, var(--app-bg-end) 340px)',
        progress: 'linear-gradient(90deg, var(--primary), var(--accent))',
      },
      transitionDuration: {
        140: '140ms',
      },
      transitionProperty: {
        interactive: 'background-color, border-color, box-shadow, color, transform',
      },
      outlineWidth: {
        3: '3px',
      },
      borderWidth: {
        3: '3px',
      },
      backdropBlur: {
        ui: '14px',
      },
      aspectRatio: {
        portrait: '2 / 3',
      },
      fontWeight: {
        'ui-semibold': '650',
        'ui-bold': '750',
        'ui-extrabold': '850',
      },
      lineHeight: {
        'ui-tight': '1.15',
        ui: '1.45',
      },
      opacity: {
        55: '0.55',
        65: '0.65',
      },
      keyframes: {
        'loading-spin': {
          to: { transform: 'rotate(360deg)' },
        },
        'job-progress-sweep': {
          '0%': { transform: 'translateX(-110%)' },
          '100%': { transform: 'translateX(260%)' },
        },
      },
      animation: {
        'loading-spin': 'loading-spin 780ms linear infinite',
        'job-progress-sweep': 'job-progress-sweep 1.1s ease-in-out infinite',
      },
      zIndex: {
        18: '18',
        20: '20',
        25: '25',
        40: '40',
        45: '45',
        60: '60',
        80: '80',
      },
    },
  },
  plugins: [
    plugin(({ addBase }) => {
      addBase({
        ':root': {
          ...lightTheme,
          color: lightTheme['--ink'],
          background: lightTheme['--app-bg-end'],
          colorScheme: 'light',
        },
        ":root[data-theme='dark']": {
          ...darkTheme,
          color: darkTheme['--ink'],
          background: darkTheme['--app-bg-end'],
          colorScheme: 'dark',
        },
      })
    }),
  ],
}
