name: Build and Publish Docker Images

on:
  push:
    branches:
      - dev
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z0-9]+)?'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      GHCR_OWNER: lofter1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image tag
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "branch" && "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "TAG=dev-latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -----------------------------
      # Build frontend (JS/Flutter web)
      - name: Build & push frontend
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/$GHCR_OWNER/frontend:${TAG} \
            ./frontend \
            --push

      # -----------------------------
      # Build metron-proxy
      - name: Build & push metron-proxy
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/$GHCR_OWNER/metron-proxy:${TAG} \
            ./metron_proxy \
            --push

      # -----------------------------
      # Build pocketbase (pass ARCH per platform)
      - name: Build & push pocketbase
        run: |
          for arch in amd64 arm64; do
            docker buildx build \
              --platform linux/$arch \
              -t ghcr.io/$GHCR_OWNER/pocketbase:${TAG}-$arch \
              ./pocketbase \
              --build-arg ARCH=$arch \
              --push
          done
